// Generated by LiveScript 1.4.0
(function(){
  var ribcage, colors, _, Backbone, env, settings;
  ribcage = require('ribcage');
  colors = require('colors');
  _ = require('underscore');
  Backbone = require('backbone4000');
  env = {};
  settings = {
    module: {
      express4: {
        port: 4000
      }
    }
  };
  env.settings = settings;
  ribcage.init(env, function(err, modules){
    env.modules = modules;
    return console.log('ribcage init', err);
  });
}).call(this);
