// Generated by LiveScript 1.4.0
(function(){
  var ribcage, colors, _, Backbone, env, settings;
  ribcage = require('ribcage');
  colors = require('colors');
  _ = require('underscore');
  Backbone = require('backbone4000');
  env = {};
  settings = {
    module: {
      express4: {
        port: 4000,
        views: __dirname + '/ejs',
        'static': __dirname + '/static'
      }
    }
  };
  env.settings = settings;
  ribcage.init(env, function(err, modules){
    console.log('initialized');
    env.modules = modules;
    return env.app.get('/', function(req, res){
      return res.render('index', {
        title: 'skeleton'
      });
    });
  });
}).call(this);
